In [1]:
 import numpy as np

In [2]:
print(np.__version__)
np.show_config()

1.11.0
atlas_info:
  NOT AVAILABLE
lapack_info:
    libraries = ['lapack', 'lapack']
    language = f77
    library_dirs = ['/usr/lib']
openblas_info:
  NOT AVAILABLE
blas_info:
    libraries = ['blas', 'blas']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
    library_dirs = ['/usr/lib']
atlas_blas_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
blas_opt_info:
    libraries = ['blas', 'blas']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    library_dirs = ['/usr/lib']
lapack_opt_info:
    libraries = ['lapack', 'lapack', 'blas', 'blas']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    library_dirs = ['/usr/lib']
mkl_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NO

In [3]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [4]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [5]:
numpy.info(numpy.add)

NameError: name 'numpy' is not defined

In [6]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [7]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
 Z = np.arange(50)
 Z = Z[::-1]
 print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [9]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [11]:
Z = np.eye(3)
print(Z)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [12]:
Z = np.random.random((3,3,3))
print(Z)

[[[ 0.63311864  0.84009741  0.45738574]
  [ 0.86782589  0.76730858  0.91041956]
  [ 0.53294308  0.10576904  0.02689238]]

 [[ 0.55042226  0.66940577  0.92649509]
  [ 0.22677341  0.57548512  0.8909927 ]
  [ 0.73980236  0.22672009  0.49638485]]

 [[ 0.07427478  0.08627835  0.13309553]
  [ 0.86123589  0.7502913   0.18491503]
  [ 0.54047992  0.35370712  0.32078929]]]


In [13]:
 Z = np.random.random((10,10))
 Zmin, Zmax = Z.min(), Z.max()
 print(Zmin, Zmax)

0.0128325375338 0.996084196529


In [15]:
 Z = np.random.random(30)
 m = Z.mean()
 print(m)

0.49967641514


In [16]:
 Z = np.ones((10,10))
 Z[1:-1,1:-1] = 0
 print(Z)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [17]:
 Z = np.ones((5,5))
 Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
 print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [18]:
print(0 * np.nan)

nan


In [19]:
print(np.nan == np.nan)

False


In [20]:
print(np.inf > np.nan)

False


In [21]:
print(np.nan - np.nan)

nan


In [22]:
print(0.3 == 3 * 0.1)

False


In [23]:
 Z = np.diag(1+np.arange(4),k=-1)
 print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [24]:
 Z = np.zeros((8,8),dtype=int)
 Z[1::2,::2] = 1
 Z[::2,1::2] = 1
 print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [25]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [26]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [27]:
 Z = np.random.random((5,5))
 Zmax, Zmin = Z.max(), Z.min()
 Z = (Z - Zmin)/(Zmax - Zmin)
 print(Z)

[[ 0.3501994   0.8288974   0.80592166  0.21024496  0.67604593]
 [ 0.14851181  0.19329611  0.06116596  0.6141613   0.54561676]
 [ 0.8403715   0.03180567  0.08872571  0.91227754  1.        ]
 [ 0.92874843  0.03341471  0.65840196  0.88565992  0.65720632]
 [ 0.          0.28642471  0.47152077  0.01643021  0.32195444]]


In [28]:
 color = np.dtype([("r", np.ubyte, 1),
                   ("g", np.ubyte, 1),
                   ("b", np.ubyte, 1),
                   ("a", np.ubyte, 1)])
 color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [29]:
 Z = np.dot(np.ones((5,3)), np.ones((3,2)))
 print(Z)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


In [30]:
 Z = np.arange(11)
 Z[(3 < Z) & (Z <= 8)] *= -1
 print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [31]:
print(sum(range(5),-1))

9


In [32]:
from numpy import *
print(sum(range(5),-1))

10


In [33]:
 Z = np.arange(5)
 Z ** Z   legal

SyntaxError: invalid syntax (<ipython-input-33-f48a8ae6a855>, line 2)

In [34]:
print(np.array(0) / np.array(0))

nan


/home/pyxuexi/.local/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [35]:
 Z = np.random.uniform(-10,+10,10)
 print (np.copysign(np.ceil(np.abs(Z)), Z))

[  6.   1.  -4.  10.  -8.   7.  -7.  -2.  -4.  -8.]


In [36]:
 Z1 = np.random.randint(0,10,10)
 Z2 = np.random.randint(0,10,10)
 print(np.intersect1d(Z1,Z2))

[3 6]


In [37]:
 Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

 Back to sanity
_ = np.seterr(**defaults)

An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

SyntaxError: invalid syntax (<ipython-input-37-eed549ab12bc>, line 1)

In [38]:
 yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
 today     = np.datetime64('today', 'D')
 tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
 print ("Yesterday is " + str(yesterday))
 print ("Today is " + str(today))
 print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-06-25
Today is 2019-06-26
Tomorrow is 2019-06-27


In [39]:
 Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
 print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [40]:
 A = np.ones(3)*1
 B = np.ones(3)*2
 C = np.ones(3)*3
 np.add(A,B,out=B)

array([ 3.,  3.,  3.])

In [41]:
 Z = np.zeros((5,5))
 Z += np.arange(5)
 print (Z)

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


In [42]:
 def generate():
     for x in range(10):
         yield x
 Z = np.fromiter(generate(),dtype=float,count=-1)
 print (Z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
